* pokemon-go

** Introduction
Congratulations and welcome to pokemon-go, one of the best programming
languages.

pokemon-go is a proprietary programming language that makes it easy to build
simple, reliable, and efficient software.

** Getting started
*** Dependencies
You must first install [[https://github.com/golang][go]] or else nothing will work.

Download the famed pokemon-go binary executable from our latest release and
place it somewhere on your path.

#+BEGIN_SRC bash
chmod +x pokemon-go
sudo mv pokemon-go /usr/local/bin
#+END_SRC

Then run ~pokemon-go~ for further instructions.

*** Building from source
If you're a nerd and can't be bothered to download our latest release, clone
this repo, then run ~go build~ and then place the created binary executable on
your path.


*** Usage
Run ~pokemon-go~ for usage instructions.

Try running one of our [[./examples/][example programs]] for inspiration.

** Documentation

Please find below a guide to pokemon-go usage. We include a comparison with
similar commands in the older, inferior go language.

| pokemon-go | go          |
|------------+-------------|
| snorlax    | break       |
| diglett    | case        |
| psyduck    | chan        |
| geodude    | const       |
| clink      | continue    |
| squirtle   | default     |
| kakuna     | defer       |
| unown      | else        |
| sandshrew  | fallthrough |
| forretress | for         |
| exeggcutor | func        |
| pikachu    | go          |
| alakazam   | goto        |
| chansey    | if          |
| goldeen    | import      |
| poliwag    | interface   |
| meowth     | map         |
| slowbro    | package     |
| gengar     | range       |
| eevee      | return      |
| scyther    | select      |
| onyx       | struct      |
| dugtrio    | switch      |
| togepi     | type        |
| jynx       | var         |

** Contribution Guidelines
 pokemon-go is *closed source* and all attempts at contribution will be met with
 swift and harsh retribution according to the terms described in the pokemon-go
 license.
